/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'chatbot',
    path: '/chatbot',
    component: 'layout.base$view.chatbot',
    meta: {
      title: 'chatbot',
      i18nKey: 'route.chatbot',
      icon: 'mdi:robot-happy-outline',
      order: 5
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system1',
    path: '/system1',
    component: 'layout.base$view.system1',
    meta: {
      title: 'system1',
      i18nKey: 'route.system1',
      icon: 'mdi:human-male-board',
      order: 1
    }
  },
  {
    name: 'system2',
    path: '/system2',
    component: 'layout.base$view.system2',
    meta: {
      title: 'system2',
      i18nKey: 'route.system2',
      icon: 'mdi:book-education-outline',// clipboard-edit-outline book-education-outline
      order: 2
    }
  },
  {
    name: 'system3',
    path: '/system3',
    component: 'layout.base$view.system3',
    meta: {
      title: 'system3',
      i18nKey: 'route.system3',
      icon: 'mdi:monitor-account',
      order: 3
    }
  },
  {
    name: 'system4',
    path: '/system4',
    component: 'layout.base$view.system4',
    meta: {
      title: 'system4',
      i18nKey: 'route.system4',
      icon: 'mdi:comment-text-multiple-outline',
      order: 4
    }
  }
];
