/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'ri:home-6-fill',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system1',
    path: '/system1',
    component: 'layout.base',
    meta: {
      title: 'system1',
      i18nKey: 'route.system1',
      icon: 'iconoir:book-solid',
      order: 1
    },
    children: [
      {
        name: 'system1_child1',
        path: '/system1/child1',
        component: 'view.system1_child1',
        meta: {
          title: 'system1_child1',
          i18nKey: 'route.system1_child1',
          icon: 'mingcute:pencil-2-ai-fill'
        }
      },
      {
        name: 'system1_child2',
        path: '/system1/child2',
        component: 'view.system1_child2',
        meta: {
          title: 'system1_child2',
          i18nKey: 'route.system1_child2',
          icon: 'ri:dashboard-fill'
        }
      },
      {
        name: 'system1_child3',
        path: '/system1/child3',
        component: 'view.system1_child3',
        meta: {
          title: 'system1_child3',
          i18nKey: 'route.system1_child3',
          icon: 'material-symbols:smb-share'
        }
      },
      {
        name: 'system1_child4',
        path: '/system1/child4',
        component: 'view.system1_child4',
        meta: {
          title: 'system1_child4',
          i18nKey: 'route.system1_child4',
          icon: 'material-symbols:handshake'
        }
      }
    ]
  },
  {
    name: 'system2',
    path: '/system2',
    component: 'layout.base',
    meta: {
      title: 'system2',
      i18nKey: 'route.system2',
      icon: 'mingcute:presentation-2-fill',
      order: 2
    },
    children: [
      {
        name: 'system2_child1',
        path: '/system2/child1',
        component: 'view.system2_child1',
        meta: {
          title: 'system2_child1',
          i18nKey: 'route.system2_child1',
          icon: 'mingcute:presentation-1-fill'
        }
      },
      {
        name: 'system2_child2',
        path: '/system2/child2',
        component: 'view.system2_child2',
        meta: {
          title: 'system2_child2',
          i18nKey: 'route.system2_child2',
          icon: 'mdi:account-box'
        }
      }
    ]
  },
  {
    name: 'system3',
    path: '/system3',
    component: 'layout.base',
    meta: {
      title: 'system3',
      i18nKey: 'route.system3',
      icon: 'icon-park-solid:comments',
      order: 3
    },
    children: [
      {
        name: 'system3_child1',
        path: '/system3/child1',
        component: 'view.system3_child1',
        meta: {
          title: 'system3_child1',
          i18nKey: 'route.system3_child1',
          icon: 'mdi:human-greeting-variant'
        }
      },
      {
        name: 'system3_child2',
        path: '/system3/child2',
        component: 'view.system3_child2',
        meta: {
          title: 'system3_child2',
          i18nKey: 'route.system3_child2',
          icon: 'mdi:text-box-edit'
        }
      }
    ]
  },
  {
    name: 'system4',
    path: '/system4',
    component: 'layout.base$view.system4',
    meta: {
      title: 'system4',
      i18nKey: 'route.system4',
      icon: 'mingcute:user-star-fill',
      order: 5
    }
  },
  {
    name: 'system6',
    path: '/system6',
    component: 'layout.base',
    meta: {
      title: 'system6',
      i18nKey: 'route.system6',
      icon: 'mdi:book-variant',
      order: 4
    },
    children: [
      {
        name: 'system6_child1',
        path: '/system6/child1',
        component: 'view.system6_child1',
        meta: {
          title: 'system6_child1',
          i18nKey: 'route.system6_child1',
          icon: 'uis:layer-group'
        }
      },
      {
        name: 'system6_child2',
        path: '/system6/child2',
        component: 'view.system6_child2',
        meta: {
          title: 'system6_child2',
          i18nKey: 'route.system6_child2',
          icon: 'mdi:book-open-page-variant'
        }
      }
    ]
  }
];
